### ISSUE TITLE
this isn't a module

### ISSUE THREAD

**Issue by NHQ** [iLanguage/iLanguage#19]
This is published to NPM.  So why can't I require this module in a node program?

**Comment by cesine** [comment]
it looks like you are making text clouds? i tried installing the ilanguage clouds instead but its not in npm 

$ npm install ilanguage-cloud --save
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ilanguage-cloud" "--save"
npm ERR! node v0.12.4
npm ERR! npm  v2.12.1
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ilanguage-cloud
npm ERR! 404
npm ERR! 404 'ilanguage-cloud' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'test'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by NHQ** [comment]
I don't know about a text cloud.  I was trying to use this repo.  But require causes an error, no module found even if it's been installed by NPM.  version 5.0.0 is published.  looks a lot different than the repo, but idk your build process.

But there should be no reason I can't run this a node context as well as a browser (with browserify), as long as you're following normal rules for exporting and packaging for NPM.

thx!

**Comment by cesine** [comment]
i checked the npm package, it was published 2 years ago and we haven't published since. :( we use master for our projects, and we didn't think anyone else would want to use it. I'll check to see if the master is stable enough to publish again. 

based on what I saw in your `text-clouds` project, probably this is the best examples of how you can use it for your texts https://github.com/iLanguage/iLanguage/blob/master/test/lexicon/ContentfulStemmer-spec.js

**Comment by cesine** [comment]
@NHQ its published from master now and should be usable, although i'm still not sure if you'll like it :) its mostly just stuff we were using internally...

```
$ npm install ilanguage
$ tree node_modules/ilanguage/ -L 2
node_modules/ilanguage/
├── CHANGELOG.md
├── LICENSE
├── README.md
├── cpp
│   ├── Framer.cpp
│   ├── Framer.h
│   ├── Language.cpp
│   ├── Language.h
│   ├── MorphoParserDriver.cpp
│   ├── NaturalLanguageMenuItem.cpp
│   ├── NaturalLanguageMenuItem.h
│   ├── OrderedProbability.cpp
│   ├── OrderedProbability.h
│   ├── Tokenizer.cpp
│   ├── Tokenizer.h
│   ├── UserInterface.cpp
│   ├── UserInterface.h
│   ├── WordCounter.cpp
│   └── WordCounter.h
├── js
│   ├── app.js
│   ├── core
│   ├── corpus
│   ├── ilanguage.js
│   ├── lexicon
│   └── shellPromises.js
├── node_modules
│   ├── collections
│   ├── fielddb
│   └── q
└── package.json
```
